### ISSUE TITLE
error: cannot parse '1.1' as a semver

### ISSUE THREAD

**Issue by dmitri-mamrukov** [errmac-v/cargo-build-dependencies#5]
I received this error:

Start building packages
Building package: "actix-rt:1.1"
error: cannot parse '1.1' as a semver
thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-build-dependencies-0.1.1/src/main.rs:98:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR: Service 'router' failed to build: The command '/bin/sh -c cargo build-dependencies' returned a non-zero code: 101

**Comment by 0xmad** [comment]
Should be fixed in `0.1.3`. Please, feel free to reopen in case if there are any problems.
